In [19]:
import numpy as np

array1 = np.array([])
array1

array([], dtype=float64)

In [20]:
array1 = np.array([1, 2, 3])
print(array1.shape)
array1.dtype

(3,)


dtype('int32')

In [24]:
array1 = np.array([1, 2, 3]).astype(float)
print(array1.shape)
array1.dtype

(3,)


dtype('float64')

In [21]:
array2 = np.array([[2.0, 3, 4], [5, 6, 7], [3, 0, 4]])
print(array2.shape)
array2.dtype

(3, 3)


dtype('float64')

In [22]:
array2.size

9

In [23]:
array2.ndim

2

In [25]:
array2.T

array([[2., 5., 3.],
       [3., 6., 0.],
       [4., 7., 4.]])

In [27]:
array2.flatten()

array([2., 3., 4., 5., 6., 7., 3., 0., 4.])

In [29]:
array3 = (
    np.array([5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]).astype(float).reshape(3, 4)
)
array3

array([[ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.],
       [13., 14., 15., 16.]])